#!/bin/bash

JOB=apache2
RUN_DIR=/var/vcap/sys/run/apache2
LOG_DIR=/var/vcap/sys/log/apache2
PIDFILE=$RUN_DIR/httpd.pid
CONF_DIR=/var/vcap/jobs/$JOB/config
APACHECTL=/var/vcap/packages/apache2/bin/apachectl
APSTART=/var/vcap/sys/log/apache2/start.log
NFS_SHARE=/var/vcap/shared

case $1 in

  start)
    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR
    mkdir -p /var/vcap/packages/wordpress
    # link libphp into apache
    if [ ! -f /var/vcap/packages/apache2/modules/libphp5.so ]; then
      ln -s /var/vcap/packages/php5/modules/libphp5.so \
        /var/vcap/packages/apache2/modules/libphp5.so
    fi   

    $APACHECTL -f $CONF_DIR/httpd.conf -k start >> $APSTART 2>&1
    ;;

  stop)
    $APACHECTL -f $CONF_DIR/httpd.conf -k stop  >> $APSTART 2>&1
    ;;

  *)
  echo "Usage: ${JOB}_ctl {start|stop}" ;;
esac
exit 0
